"""
Rotating, fraud-resistant attendance tokens for webinar check-in / check-out.

The admin's attendance screen displays a QR/code derived from an HMAC of the
webinar's secret + a coarse time counter + the phase ("in"/"out"). The token
rotates every STEP seconds, so a screenshot shared ahead of time expires and a
token cannot be pre-generated by attendees. Check-in verification accepts the
current window plus a small number of previous windows to tolerate clock skew
and scan latency.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import time

TOKEN_STEP_SECONDS = 30
TOKEN_LENGTH = 8
DEFAULT_VERIFY_WINDOWS = 3

VALID_PHASES = ("in", "out")


def _counter(ts: float | None = None) -> int:
    return int((ts if ts is not None else time.time()) // TOKEN_STEP_SECONDS)


def generate_attendance_token(secret: str, phase: str, counter: int | None = None) -> str:
    """Deterministic short token for a webinar secret, phase, and time window."""
    if phase not in VALID_PHASES:
        raise ValueError(f"Invalid phase: {phase}")
    window = counter if counter is not None else _counter()
    message = f"{phase}:{window}".encode()
    digest = hmac.new(secret.encode(), message, hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode()[:TOKEN_LENGTH].upper()


def verify_attendance_token(
    secret: str,
    phase: str,
    token: str,
    *,
    windows: int = DEFAULT_VERIFY_WINDOWS,
) -> bool:
    """True if token matches the current or a recent window for this phase."""
    if not token or phase not in VALID_PHASES:
        return False
    candidate = token.strip().upper()
    now = _counter()
    for offset in range(windows):
        expected = generate_attendance_token(secret, phase, now - offset)
        if hmac.compare_digest(expected, candidate):
            return True
    return False


def seconds_until_next_window(ts: float | None = None) -> int:
    """Seconds remaining before the current token rotates (for UI countdown)."""
    now = ts if ts is not None else time.time()
    return int(TOKEN_STEP_SECONDS - (now % TOKEN_STEP_SECONDS))
