"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
import sys

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (django-environ)
try:
    import environ

    env = environ.Env()
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        environ.Env.read_env(env_file)
except ImportError:
    env = None


def get_env(key, default=None):
    """Get environment variable with optional default."""
    return os.environ.get(key, default)


def _csv_env(key, default=""):
    """Parse a comma-separated environment variable into a trimmed list."""
    raw = get_env(key, default) or default
    return [part.strip() for part in raw.split(",") if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_DEV_SECRET_KEY = (
    "django-insecure-2!d-3$fwjq)l_!adh8_$ow8&boe*mfw7#e(pmy(l27=%=qha!u"
)
_INSECURE_SECRET_KEY_PLACEHOLDERS = {
    _INSECURE_DEV_SECRET_KEY,
    "change-me",
    "change-me-to-secure-random-key",
    "change-me-to-secure-random-key-min-50-chars-gunakan-ini-di-production",
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env("DEBUG", "False").lower() in ("true", "1", "yes")

_secret_from_env = get_env("SECRET_KEY")
if _secret_from_env:
    SECRET_KEY = _secret_from_env
elif DEBUG:
    SECRET_KEY = _INSECURE_DEV_SECRET_KEY
else:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is required when DEBUG is False."
    )

if not DEBUG and SECRET_KEY in _INSECURE_SECRET_KEY_PLACEHOLDERS:
    raise ImproperlyConfigured(
        "SECRET_KEY must be set to a secure value in production."
    )

ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS", "localhost,127.0.0.1")

# CORS settings
CORS_ALLOWED_ORIGINS = _csv_env(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173",
)

# Production security settings
SECURE_SSL_REDIRECT = get_env("SECURE_SSL_REDIRECT", "False").lower() in ("true", "1", "yes")
# Allow internal HTTP probes (Docker healthcheck, deploy scripts) when SSL redirect is on.
SECURE_REDIRECT_EXEMPT = [r"^health/$"]
SESSION_COOKIE_SECURE = get_env("SESSION_COOKIE_SECURE", "False").lower() in ("true", "1", "yes")
CSRF_COOKIE_SECURE = get_env("CSRF_COOKIE_SECURE", "False").lower() in ("true", "1", "yes")
CSRF_TRUSTED_ORIGINS = _csv_env("CSRF_TRUSTED_ORIGINS") if get_env("CSRF_TRUSTED_ORIGINS") else []
FRONTEND_URL = get_env("FRONTEND_URL", "http://localhost:5173")

if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    if SECURE_SSL_REDIRECT:
        SECURE_HSTS_SECONDS = int(get_env("SECURE_HSTS_SECONDS", "31536000"))
        SECURE_HSTS_INCLUDE_SUBDOMAINS = get_env(
            "SECURE_HSTS_INCLUDE_SUBDOMAINS", "True"
        ).lower() in ("true", "1", "yes")
        SECURE_HSTS_PRELOAD = get_env("SECURE_HSTS_PRELOAD", "False").lower() in (
            "true",
            "1",
            "yes",
        )

# Mailgun API (https://documentation.mailgun.com/docs/mailgun/api-reference/)
MAILGUN_API_KEY = get_env("MAILGUN_API_KEY", "")
MAILGUN_DOMAIN = get_env("MAILGUN_DOMAIN", "")
MAILGUN_API_URL = get_env("MAILGUN_API_URL", "https://api.mailgun.net/v3")
# Optional display name; keep DEFAULT_FROM_EMAIL as the address only (no spaces needed).
MAILGUN_FROM_NAME = get_env("MAILGUN_FROM_NAME", "ITNB Hub")

_raw_from_email = (get_env("DEFAULT_FROM_EMAIL") or "").strip()
if _raw_from_email:
    if "@" in _raw_from_email and "<" not in _raw_from_email and MAILGUN_FROM_NAME:
        DEFAULT_FROM_EMAIL = f"{MAILGUN_FROM_NAME} <{_raw_from_email}>"
    else:
        DEFAULT_FROM_EMAIL = _raw_from_email
elif MAILGUN_DOMAIN:
    DEFAULT_FROM_EMAIL = f"{MAILGUN_FROM_NAME} <noreply@{MAILGUN_DOMAIN}>"
else:
    DEFAULT_FROM_EMAIL = "noreply@itnb.local"

if MAILGUN_API_KEY and MAILGUN_DOMAIN:
    # Mailgun credentials take priority over legacy console/SMTP EMAIL_BACKEND values.
    EMAIL_BACKEND = "account.backends.mailgun.MailgunEmailBackend"
else:
    EMAIL_BACKEND = get_env(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend",
    )

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI server for WebSockets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    
    # Local apps
    'account.apps.AccountConfig',
    'main.apps.MainConfig',
    'academic.apps.AcademicConfig',
]

AUTH_USER_MODEL = 'account.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Production/Docker: DATABASE_URL (postgres://...) from compose or .env
# Local dev: omit DATABASE_URL to use SQLite at BASE_DIR/db.sqlite3

if env is not None:
    DATABASES = {
        'default': env.db(
            'DATABASE_URL',
            default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }

if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default'].setdefault(
        'CONN_MAX_AGE',
        int(get_env('DATABASE_CONN_MAX_AGE', '60')),
    )
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True

# External myitnb MariaDB (read-only via PyMySQL in academic app; not Django DATABASES)
MYITNB_DB_HOST = get_env('MYITNB_DB_HOST', '')
MYITNB_DB_PORT = get_env('MYITNB_DB_PORT', '3306')
MYITNB_DB_NAME = get_env('MYITNB_DB_NAME', 'myitnb')
MYITNB_DB_USER = get_env('MYITNB_DB_USER', '')
MYITNB_DB_PASSWORD = get_env('MYITNB_DB_PASSWORD', '')
# Comma-separated curriculum record IDs for score-list query (legacy: 1,23,55)
MYITNB_CURRICULUM_IDS = get_env('MYITNB_CURRICULUM_IDS', '1,23,55')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads, generated PDFs, QR codes)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Digital card template settings
ID_CARD_FRONT_TEMPLATE_URL = get_env(
    "ID_CARD_FRONT_TEMPLATE_URL",
    f"{MEDIA_URL}cards/templates/card-bg.jpg",
)
ID_CARD_BACK_TEMPLATE_URL = get_env(
    "ID_CARD_BACK_TEMPLATE_URL",
    f"{MEDIA_URL}cards/templates/back.png",
)
ID_CARD_FRONT_TEMPLATE_PATH = get_env(
    "ID_CARD_FRONT_TEMPLATE_PATH",
    str(MEDIA_ROOT / "cards" / "templates" / "card-bg.jpg"),
)
ID_CARD_BACK_TEMPLATE_PATH = get_env(
    "ID_CARD_BACK_TEMPLATE_PATH",
    str(MEDIA_ROOT / "cards" / "templates" / "back.png"),
)
GENERATE_CARD_IMAGE_ON_CREATE = get_env("GENERATE_CARD_IMAGE_ON_CREATE", "False").lower() in ("true", "1", "yes")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# REST Framework Configuration
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'auth': '10/min',
        'auth_public': '5/min',
        'email_send': '3/hour',
        'email_send_user': '5/hour',
        'email_verify': '10/min',
    },
    'EXCEPTION_HANDLER': 'account.exceptions.custom_exception_handler',
}


# ---------------------------------------------------------------------------
# JWT Configuration
# ---------------------------------------------------------------------------

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}


# ---------------------------------------------------------------------------
# Celery Configuration (for async tasks like PDF generation)
# ---------------------------------------------------------------------------

def _default_redis_url() -> str:
    """Use Docker service hostname when the app runs in compose."""
    database_url = get_env('DATABASE_URL', '') or ''
    sql_host = get_env('SQL_HOST', '') or ''
    if '@db:' in database_url or sql_host == 'db':
        return 'redis://redis:6379/0'
    return 'redis://localhost:6379/0'


_DEFAULT_REDIS_URL = _default_redis_url()


def _default_redis_cache_url() -> str:
    """Use a separate Redis DB for Django cache (Celery uses /0)."""
    explicit = get_env('REDIS_CACHE_URL', '')
    if explicit:
        return explicit
    base = _DEFAULT_REDIS_URL.rstrip('/')
    if base.endswith('/0'):
        return f"{base[:-1]}1"
    return f"{base}/1"


# Throttle state must be shared across workers (use Redis in dev/prod).
if 'test' in sys.argv:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _default_redis_cache_url(),
        },
    }

CELERY_BROKER_URL = get_env('CELERY_BROKER_URL', _DEFAULT_REDIS_URL)
CELERY_RESULT_BACKEND = get_env('CELERY_RESULT_BACKEND', _DEFAULT_REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Jakarta'

# Queue transactional email via Celery (set false to send inline, e.g. debugging)
EMAIL_DELIVERY_ASYNC = get_env('EMAIL_DELIVERY_ASYNC', 'True').lower() in ('true', '1', 'yes')

if 'test' in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True


# ---------------------------------------------------------------------------
# Channel Layers (for WebSocket support if needed)
# ---------------------------------------------------------------------------

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [get_env('REDIS_CHANNEL_URL') or get_env('CELERY_BROKER_URL') or _DEFAULT_REDIS_URL],
        },
    },
}

ASGI_APPLICATION = 'backend.asgi.application'


# ---------------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------------

def _active_log_handlers():
    """Use file logging only when the logs directory is writable (bind mounts on Windows may not be)."""
    handlers = ['console']
    log_file = BASE_DIR / 'logs' / 'django.log'
    try:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        with open(log_file, 'a', encoding='utf-8'):
            pass
        handlers.append('file')
    except OSError:
        pass
    return handlers


_ACTIVE_LOG_HANDLERS = _active_log_handlers()

_LOG_HANDLERS = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'simple',
    },
}
if 'file' in _ACTIVE_LOG_HANDLERS:
    _LOG_HANDLERS['file'] = {
        'class': 'logging.FileHandler',
        'filename': BASE_DIR / 'logs' / 'django.log',
        'formatter': 'verbose',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': _LOG_HANDLERS,
    'root': {
        'handlers': _ACTIVE_LOG_HANDLERS,
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': _ACTIVE_LOG_HANDLERS,
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'account': {
            'handlers': _ACTIVE_LOG_HANDLERS,
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
