# Generated by Django 5.2.13 on 2026-04-20 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Used for login and notifications.', max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, help_text="User's complete name.", max_length=255, verbose_name='full name')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student'), ('ALUMNI', 'Alumni')], db_index=True, default='STUDENT', help_text='Determines access level and profile type.', max_length=8, verbose_name='role')),
                ('photo', models.ImageField(blank=True, help_text='User profile picture.', null=True, upload_to='profile_photos/%Y/%m/', verbose_name='profile photo')),
                ('department', models.CharField(blank=True, help_text='Department (for Staff/Lecturer).', max_length=100, verbose_name='department')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When user joined the institution.', verbose_name='date joined')),
                ('alumni_year', models.IntegerField(blank=True, help_text='Graduation year (for Alumni only).', null=True, verbose_name='alumni year')),
                ('email_verified', models.BooleanField(db_index=True, default=False, help_text='Whether email has been verified.', verbose_name='email verified')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of email verification.', null=True, verbose_name='email verified at')),
                ('google_id', models.CharField(blank=True, db_index=True, help_text='Google OAuth ID for social login.', max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-is_active', 'email'],
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(blank=True, help_text='Year of graduation.', null=True, verbose_name='graduation year')),
                ('graduation_date', models.DateField(blank=True, help_text='Date of graduation.', null=True, verbose_name='graduation date')),
                ('alumni_membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Alumni membership status.', max_length=50, verbose_name='membership status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ALUMNI'}, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alumni profile',
                'verbose_name_plural': 'alumni profiles',
            },
        ),
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, help_text='Unique identifier for the card.', max_length=50, unique=True, verbose_name='card number')),
                ('card_type', models.CharField(choices=[('STUDENT', 'Student Card'), ('LECTURER', 'Staff Card'), ('STAFF', 'Staff Card'), ('ALUMNI', 'Alumni Card')], help_text='Type of card (auto-derived from user role).', max_length=20, verbose_name='card type')),
                ('qr_code', models.ImageField(help_text='QR code image for card verification.', upload_to='qr_codes/%Y/%m/', verbose_name='QR code')),
                ('card_image', models.ImageField(blank=True, help_text='Generated digital card image.', null=True, upload_to='cards/%Y/%m/', verbose_name='card image')),
                ('valid_until', models.DateField(help_text='Card expiration date.', verbose_name='valid until')),
                ('is_active', models.BooleanField(default=True, help_text='Whether card is currently valid and active.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'digital card',
                'verbose_name_plural': 'digital cards',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='6-digit kode verifikasi email.', max_length=6, verbose_name='kode verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Waktu kedaluwarsa kode.', verbose_name='kedaluwarsa pada')),
                ('is_used', models.BooleanField(default=False, help_text='Kode sudah diverifikasi.', verbose_name='sudah digunakan')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Jumlah percobaan verifikasi gagal.', verbose_name='percobaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'kode verifikasi email',
                'verbose_name_plural': 'kode verifikasi email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, help_text='Nomor HP/WA yang aktif.', max_length=50, verbose_name='no. HP / WA yang aktif')),
                ('address', models.TextField(blank=True, verbose_name='alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'LECTURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'profil dosen',
                'verbose_name_plural': 'daftar profil dosen',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(blank=True, help_text='e.g., Academic Administrator, Finance Officer.', max_length=100, verbose_name='staff role')),
                ('can_issue_certificates', models.BooleanField(default=False, help_text='Whether this staff can issue/revoke certificates.', verbose_name='can issue certificates')),
                ('can_manage_benefits', models.BooleanField(default=False, help_text='Whether this staff can manage benefits directory.', verbose_name='can manage benefits')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff profile',
                'verbose_name_plural': 'staff profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='account_cus_role_8abfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'is_active'], name='account_cus_email_36ea05_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalcard',
            index=models.Index(fields=['card_number'], name='account_dig_card_nu_2b9458_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalcard',
            index=models.Index(fields=['user', 'is_active'], name='account_dig_user_id_6d88c2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['user', 'is_used'], name='account_ema_user_id_de7b13_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['code', 'is_used'], name='account_ema_code_e3ae4b_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerprofile',
            index=models.Index(fields=['user'], name='account_lec_user_id_ff5401_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerprofile',
            index=models.Index(fields=['address'], name='account_lec_address_c759ce_idx'),
        ),
    ]
