# Generated by Django 5.2.13 on 2026-04-20 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='benefit title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_short', models.CharField(blank=True, max_length=200, verbose_name='short description')),
                ('partner', models.CharField(blank=True, max_length=255, verbose_name='partner')),
                ('image_url', models.URLField(blank=True, verbose_name='cover image URL')),
                ('eligible_roles', models.CharField(default='STUDENT,LECTURER,STAFF,ALUMNI', max_length=255, verbose_name='eligible roles')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefits', to='main.benefitcategory')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='judul')),
                ('message', models.TextField(verbose_name='pesan')),
                ('notification_type', models.CharField(choices=[('INFO', 'Informasi'), ('SUCCESS', 'Sukses'), ('WARNING', 'Peringatan'), ('ERROR', 'Error'), ('BROADCAST', 'Broadcast')], db_index=True, default='INFO', max_length=20, verbose_name='tipe')),
                ('priority', models.CharField(choices=[('LOW', 'Rendah'), ('NORMAL', 'Normal'), ('HIGH', 'Tinggi'), ('URGENT', 'Mendesak')], db_index=True, default='NORMAL', max_length=10, verbose_name='prioritas')),
                ('recipient_config', models.JSONField(default=dict, verbose_name='konfigurasi penerima')),
                ('send_email', models.BooleanField(default=False, verbose_name='kirim email')),
                ('send_push', models.BooleanField(default=True, verbose_name='kirim push notification')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='dijadwalkan pada')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='dikirim pada')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total penerima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='certificate title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image_url', models.URLField(blank=True, verbose_name='cover image URL')),
                ('issued_date', models.DateField(verbose_name='issued date')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='PDF file')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('issued_by', models.ForeignKey(limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='judul')),
                ('message', models.TextField(verbose_name='pesan')),
                ('notification_type', models.CharField(choices=[('INFO', 'Informasi'), ('SUCCESS', 'Sukses'), ('WARNING', 'Peringatan'), ('ERROR', 'Error'), ('BROADCAST', 'Broadcast')], db_index=True, default='INFO', max_length=20, verbose_name='tipe')),
                ('priority', models.CharField(choices=[('LOW', 'Rendah'), ('NORMAL', 'Normal'), ('HIGH', 'Tinggi'), ('URGENT', 'Mendesak')], db_index=True, default='NORMAL', max_length=10, verbose_name='prioritas')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='URL aksi')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name='label aksi')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='sudah dibaca')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='dibaca pada')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email terkirim')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='email terkirim pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='dibuat pada')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.broadcast', verbose_name='broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='content')),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('NEWS', 'News'), ('EVENT', 'Event'), ('ACADEMIC', 'Academic')], default='ANNOUNCEMENT', max_length=50, verbose_name='category')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', verbose_name='cover image')),
                ('image_url', models.URLField(blank=True, verbose_name='cover image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(limit_choices_to={'role__in': ['LECTURER', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='event date & time')),
                ('event_location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='capacity')),
                ('rsvp_count', models.IntegerField(default=0, editable=False, verbose_name='RSVP count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='main.post')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
