# Generated by Django 5.2.13 on 2026-07-01 09:50

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certificate_layout_and_suspend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'In-person'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=10, verbose_name='mode')),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('online_url', models.URLField(blank=True, verbose_name='online meeting URL')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True, verbose_name='registration opens at')),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='registration closes at')),
                ('auto_issue_certificate', models.BooleanField(default=True, help_text='Issue a certificate automatically once an attendee checks in.', verbose_name='auto-issue certificate on check-in')),
                ('attendance_secret', models.CharField(default=main.models.generate_attendance_secret, max_length=64, verbose_name='attendance signing secret')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('certificate_program', models.ForeignKey(blank=True, help_text='Template used to auto-issue certificates to attendees.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='main.certificateprogram')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='main.post')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=20, verbose_name='status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='checked out at')),
                ('check_in_method', models.CharField(blank=True, max_length=20, verbose_name='check-in method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinar_registration', to='main.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.webinar')),
            ],
            options={
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('webinar', 'user'), name='uniq_webinar_user')],
            },
        ),
    ]
